portal/adminpanel/urls.py
"""ADMIN SPECIFIC URLS"""

'''---------------------------------------------------------------------------------------------------------------------'''

#Django Import.
from django.conf.urls import include,url

'''---------------------------------------------------------------------------------------------------------------------'''

#Views imports.
from .views import *

'''---------------------------------------------------------------------------------------------------------------------'''

urlpatterns = [

	url(r'rank_list/' , StartUpRank , name = 'Rank_List'),
	url(r'startups/requests/$', StartupRequest, name = 'startup_requests'),
	url(r'startups/(?P<startup_name>\w+)/$', StartupDetail, name = 'startup_detail'),
	url(r'startups/add/startup', AddStartup, name='add_startup'),
	url(r'startups/add/founders', AddFounder, name='add_founder'),
	url(r'startups/approve/(?P<startup_name>\w+)/$',StartupApprove, name='startup_approval'),
	url(r'add_event/', AddEvent, name = 'add_event')


]

portal/portal/urls.py
# Django imports
from django.conf.urls import include, url
from django.contrib import admin

# Function Imports(Views)


from users.views import *
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# from resources.views import ResourceHandler
from events.views import EventHandler, EventDetails

# Rest Framework Imports
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# Url Imports.
from users import urls as users_urls
from startups import urls as startup_urls
from posts import urls as post_urls
from events import urls as event_urls
from dashboard import urls as  dashboard_urls
from users.views import AddFounderfromForm
from startups.views import AddStartupfromForm

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # Rest Framework Urls
    url(r'^auth-api/'			, include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/' 	, views.obtain_auth_token),
    url(r'^docs/'				, include('rest_framework_swagger.urls')),

    # user urls
    url(r'^api/user/' 			, include(users_urls)),
    url(r'^api/events/' 		, include(event_urls)),
    url(r'^api/startups/' 		, include(startup_urls)),
    url(r'^api/posts/' 			, include(post_urls)),
    url(r'^dashboard/' 			, include(dashboard_urls)),

    url(r'^user/addfounder' 	, AddFounderfromForm, name='add_founder_from_form'),
    url(r'^startup/addstartup' 	, AddStartupfromForm, name='add_startup'),
    url(r'^approvalrequest/' 	, InApproval, name='in_approval')

]

urlpatterns = format_suffix_patterns(urlpatterns)

portal/posts/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from posts.views import *


urlpatterns = [
    url(r'posts_list/$'         , PostHandler.as_view() , name = 'posts-list'),
    url(r'edit_post/$'          , EditPost, name='edit-post'),
    url(r'news_feed/'           , NewsFeed, name='news_feed'),
    # url(r'influencer_feed/'   , InfluencerNewsFeed, name = 'influencer-news-feed'),
    url(r'comments/$'           , CommentHandler.as_view(), name='CommentHandler'),
    url(r'comment_edit/$'       , EditComment, name='editComment'),
    url(r'like_or_comment/$'    , liker_or_comments, name='likes_or_comments'),
    url(r'like_or_unlike/$'     , LikeorUnlike.as_view(), name='like_or_unlike'),
    url(r'myposts/$'            , MyPosts,  name='my_posts'),
    url(r'confession_post'		, ConfessionPostCreate, name='confession_posts'),
    url(r'confession_news_feed'	, ConfessionNewsFeed, name='confession_news_feed'),
    url(r'confession_upvote'	, ConfessionUpvoteorDownvote, name='confession_upvote_downvote')
    ]

portal/adminpanel/models.py
from django.db import models

# Create your models here.

portal/events/forms.py
#Django Related imports
from django import forms



class AddEventForm(forms.Form):
    name_of_event   = forms.CharField(max_length = 200, label='Name of Event :')
    hosted_by       = forms.CharField(max_length = 100 , required = True)
    description     = forms.CharField(widget=forms.Textarea, required = True)
    location        = forms.CharField(max_length = 100)
    start_date      = forms.DateField(widget=forms.TextInput(attrs=
                                { 'class':'datepicker'}),
                                required = True)
    end_date        = forms.DateField(widget=forms.TextInput(attrs=
                                { 'class':'datepicker'})
    ,required = True)
    public_url      = forms.URLField(max_length = 500 , required = False)
    event_image     = forms.FileField(required = False)

portal/users/forms.py
# Django Related imports
from django import forms

# Model imports

from startups.models import startUp


class AddUserForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)
    email = forms.EmailField(required=True)
    image = forms.FileField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_handle = forms.URLField(required=False)
    startup = forms.ModelChoiceField(queryset=startUp.objects.all())
    add_another_founder = forms.BooleanField(required=False)
    about = forms.CharField(widget=forms.Textarea, required=False)

portal/adminpanel/views.py
'''--------------------------------------------------------------------------------------'''

#Django Package imports. 
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.utils.crypto import get_random_string
import boto.ses
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse , JsonResponse
from django.views.decorators.csrf import csrf_exempt

import traceback
from portal import boto_helper
from portal.settings import S3_ACCESS_KEY, S3_BUCKET_NAME, S3_SECRET_ACCESS_KEY,\
                            user_images_file_path, startup_images_file_path, events_images_file_path
import os 

from PIL import Image
from io import StringIO
'''--------------------------------------------------------------------------------------'''

#Model Imports.
from posts.models import post
from startups.models import startUp
from events.models import * 
'''--------------------------------------------------------------------------------------'''

#Rest Framework Imports.
from rest_framework.response import Response

'''--------------------------------------------------------------------------------------'''

#Form Imports
from startups.forms import * 
from users.forms import *
from events.forms import * 

'''--------------------------------------------------------------------------------------'''


'''StartUp Ranking list View. FBV.'''
@login_required
@csrf_exempt
def StartUpRank(request):
    """
        Function to publish or unpublish ranks for top ten startups on the App.
    """
    if request.method == "GET":
        r_startups = startUp.objects.filter(trending = True)
        u_startups = startUp.objects.filter(trending = False)
        context = {
            'r_startups' : r_startups,
            'u_startups' : u_startups,
            }
        
        return render(request,'adminpanel/startup_ranking.html',context)

    elif request.method == "POST": 

        try:
            
            unpublish = startUp.objects.filter(trending = True)
            '''Reset current rank list.'''
            for u in unpublish:
                u.trending = False
                u.rank = None
                u.save()
            
            i = 1
            '''Set Current Rank List.'''
            for u in request.POST.getlist("publish_array"): 
                startup = startUp.objects.get(name_of_startup = u)
                startup.trending = True
                startup.rank = i
                startup.save()
                i= i+1

            return JsonResponse({'success' : True})
        except Exception as e :
            return JsonResponse({"success" : False})

def StartupRequest(request):

    '''
        Function for a list of startups whose request is pending 
        or whose request has been approved
    '''

    approved_startups = startUp.objects.filter(approval_status='Approved')
    pending_startups = startUp.objects.filter(approval_status='Pending')

    context = {
            'approved_startups' : approved_startups,
            'pending_startups'  : pending_startups,

    }
    return render(request,'adminpanel/startuprequests.html',context)

def StartupDetail(request, startup_name):


    startup = startUp.objects.get(name_of_startup=startup_name)
    users = startup.cofounders.all()
    context = {

            'startup'   : startup,
            'users'     : users,
    }
    return render(request,'adminpanel/startupdetails.html',context)

def StartupApprove(request, startup_name):
    '''
    Function for approving the Startup
    Invite token is generated and sent to the Founders 
    '''
    
    startup = startUp.objects.get(name_of_startup=startup_name)
    users = startup.cofounders.all()
    
    startup.approval_status = True
    # establishing connection to AWS SES
    conn = boto.ses.connect_to_region(
                'us-west-2',
                aws_access_key_id='AKIAI6WOXTRMWMPR65QQ',
                aws_secret_access_key='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')

        
    for user in users:
        
        #Generating a random 8_length token string
        invite_token = get_random_string(length=8)
        
        #setting the invite token as password   
        user.set_password(invite_token)
        user.save()

        html =  '<html><head><title>Approved</title><head><body> ' +\
                '<div><p>Hello your request for Founders has been approved.'+\
                'Below are your attached username and password <br> username: '+ \
                 user.username + '<br> password: ' + invite_token +  '<br>'+ \
                'You can now login to the app <br><br>Regards<br>Founder</body></html>'
        
        
        # send mail code 
        # email id to be verified in testing process
        conn.send_email(
                'karan@grappus.com',
                'Request Approved',
                 None,
                 [user.email],
                 format='html',
                 html_body = html,
              ) 

    return render(request,'adminpanel/mail_sent.html')

@csrf_exempt
def AddStartup(request):

    
    if request.method == 'POST':


        file_path = startup_images_file_path
        
        form = AddStartupForm(request.POST , request.FILES)
        if form.is_valid():
            name_of_startup      = form.cleaned_data['name_of_startup'] 
            linkedin_url         = form.cleaned_data['linkedin_url']
            facebook_url         = form.cleaned_data['facebook_url']
            twitter_handle       = form.cleaned_data['twitter_handle']
            inc_year             = form.cleaned_data['inc_year']
            type_of_trade        = form.cleaned_data['type_of_trade']
            description          = form.cleaned_data['description']
            team_size            = form.cleaned_data['team_size']
            location             = form.cleaned_data['location']
            company_tagline      = form.cleaned_data['company_tagline']

            background_image     = request.FILES['background_image']
            
            startup_logo         = request.FILES['startup_logo']
            

            #reading background image and uploading to s3 and saving the url to databse
            background_file_name =  str(background_image)
            background_image_file = open(os.path.join(file_path, background_file_name), 'wb')
            background_image_file.write(background_image.read())
            background_image_file.close()
            background_image_path = boto_helper.upload_image(file_path, str(background_image))
            background_image_s3 = "https://s3.amazonaws.com/" + S3_BUCKET_NAME + "/" + background_file_name
            
            #reading background image and uploading to s3 and saving the url to databse
            startup_logo_file_name =  str(startup_logo)
            startup_logo_file = open(os.path.join(file_path, startup_logo_file_name), 'wb')
            startup_logo_file.write(startup_logo.read())
            startup_logo_file.close()
            startup_logo_path = boto_helper.upload_image(file_path, str(startup_logo))
            startup_logo_s3 = "https://s3.amazonaws.com/" + S3_BUCKET_NAME + "/" + startup_logo_file_name
            
            startup = startUp.objects.create(name_of_startup=name_of_startup, linkedin_url=linkedin_url, \
                            facebook_url=facebook_url, twitter_handle=twitter_handle, inc_year = inc_year,\
                            description= description, team_size=team_size, location=location,\
                            company_tagline=company_tagline, background_startup_image= background_image_s3, \
                            startup_logo = startup_logo_s3)


            return redirect('/adminpanel/startups/add/founders')
        else:
            
            return render(request,'adminpanel/addstartup.html', {'form':form, 'errors' : form.errors})

        
    else:
        form = AddStartupForm()
        return render(request,'adminpanel/addstartup.html', {'form':form})

@csrf_exempt
def AddFounder(request):


    file_path = user_images_file_path
    if request.method == 'POST':
        form = AddUserForm(request.POST , request.FILES)
        
        if form.is_valid():
            add_another_founder = form.cleaned_data['add_another_founder']
            first_name          = form.cleaned_data['first_name']
            last_name           = form.cleaned_data['last_name']
            email               = form.cleaned_data['email']
            startup             = form.cleaned_data['startup']
            linkedin_url        = form.cleaned_data['linkedin_url']
            facebook_url        = form.cleaned_data['facebook_url']
            twitter_handle      = form.cleaned_data['twitter_handle']
            image               = request.FILES['image']
            
            file_name =  str(image)
            image_file = open(os.path.join(file_path, file_name), 'wb')
            image_file.write(image.read())
            image_file.close()
            image_path = boto_helper.upload_image(file_path, str(image))
            image_s3 = "https://s3.amazonaws.com/" + S3_BUCKET_NAME + "/" + file_name

            startup = startUp.objects.get(name_of_startup = startup)
            
            user = MyUser.objects.create(username=email,email = email, first_name = first_name,\
                        last_name= last_name , facebook_url= facebook_url, linkedin_url= linkedin_url,\
                        twitter_handle = twitter_handle, image = image_s3, startup = startup)
            

            if add_another_founder:
                return redirect('/adminpanel/startups/add/founders')
            else:
                return redirect('/admin')

        else:
            return render(request,'adminpanel/addfounders.html',{'form':form,'errors':form.errors})
    else:
        form = AddUserForm()

portal/templates/adminpanel/addevent.html
<!DOCTYPE html>
{% load material_form %}
{% load staticfiles %}
<html>
<head>

	<title>Add Event</title>


	<meta charset="utf-8">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">

	<style type="text/css">
		.brand-logo
		{
			margin: 15px 40px;
		}

		.container
		{
			margin: 5rem 10rem !important;
		}


	</style>
</head>
<body>

	<nav>
		<div class="nav-wrapper">
			<a href="/admin" class="brand-logo">Admin</a>
			
		</div>
	</nav>
	<div class="container">	
		<form method="POST" action=""  enctype="multipart/form-data">


			<div>
				<label>Name of Event</label>
				<input id="id_name_of_event" maxlength="200" name="name_of_event" type="text" />
				{{ form.name_of_event.errors }} 
			</div>
			<div>
				<label>Hosted By</label>
				<input id="id_hosted_by" maxlength="100" name="hosted_by" type="text" />
			</div>
			<div>
				<label>Description</label>
				<textarea cols="40" id="id_description" name="description" rows="10">
				</textarea>
			</div>
			<div>
				<label>Location</label>
				<input id="id_location" maxlength="100" name="location" type="text" />
			</div>
			<div>
				<label>Start Date</label>

			</div>
			<div>
				<label>End Date</label>

			</div>
			<div>
				<label>Image</label>
				<input id="id_event_image" name="event_image" type="file" />
			</div>
			<div>
				<label>Public URL</label>
				<input id="id_public_url" maxlength="500" name="public_url" type="url" />
			</div>

			<a href="/admin"><input type="submit" value="Save" class="btn btn-submit" /></a>

		</form>
	</div>

</body>
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
{% include 'material/includes/material_js.html' %}
</html>

portal/templates/adminpanel/addfounders.html
<!DOCTYPE html>
{% load material_form %}
{% load staticfiles %}
<html>
<head>

	<title>Add Founder</title>

	<meta charset="utf-8">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'adminpanel/css/addfounder.css' %}">
		
	<script type="text/javascript">
		function change(e){
			console.log($('#'+e).children());
			$('#'+e).children()[1].focus();
			
		}
	</script>
</head>

<body>
	
	<nav>
		<div class="nav-wrapper">
			<a href="/admin" class="brand-logo">Admin</a>

		</div>
	</nav>

	<div class="container">	
		<form  enctype="multipart/form-data" method="POST" action="">
			{% csrf_token %}
			
			<div id="firsName" class=" row form-element" onmouseover="change(id)">
				<label id="label_first_name">First Name</label>
				{{form.first_name}}
			</div>
			<div id="lastName" class="form-element" onmouseover="change(id)">
				<label>Last Name</label>
				{{form.last_name}}
			</div>
			<div id="email" class="form-element" onmouseover="change(id)">
				<label>Email</label>
				{{form.email}}
			</div>
			<div id="image" class="row form-element" onmouseover="change(id)">
				<label>Image</label>
				{{form.image}}
			</div>
			<div id="linkedin" class="row form-element" onmouseover="change(id)">
				<label>Linkedin Url</label>
				{{form.linkedin_url}}
			</div>
			<div id="facebook" class="row form-element" onmouseover="change(id)">
				<label>Facebook Url</label>
				{{form.facebook_url}}
			</div>
			<div id="twitter" class="row form-element" onmouseover="change(id)">
				<label>Twitter Handle</label>
				{{form.twitter_handle}}
			</div>
			<div class="row form-element" onmouseover="change(id)">
			<input type="submit" value="Save " class="btn right submit "  id="save"  />
			</div>	
			<input type="submit" value="Add Another Founder " class="btn right submit"  id="add" />
		</form>
	</div> 

</body>
<script type="text/javascript">
	$(function(){
		

		$(':checkbox').change(function() {

			if ($('#id_add_another_founder').is(':checked')) {
				$('#add').show();
				$('#save').hide();
			}
			else {
				$('#add').hide();
				$('#save').show();
			}



		});



	});
</script>



</html>

portal/templates/adminpanel/addstartup.html
<!DOCTYPE html>
{% load material_form %}
{% load staticfiles %}
<html>
<head>

	<title>Add Startup</title>


	<meta charset="utf-8">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">

	<style type="text/css">
		.brand-logo
		{
			margin: 15px 40px;
		}

		.container
		{
			margin: 5rem 10rem !important;
		}


	</style>
</head>
<body>

	<nav>
		<div class="nav-wrapper">
			<a href="/admin" class="brand-logo">Admin</a>
			
		</div>
	</nav>
	<div class="container">	
		<form method="POST" action=""  enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p}}

			<a href="/adminpanel/startups/add/founders"><input type="submit" value="Save and Proceed" class="btn right" /></a>

		</form>
	</div>

</body>
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
{% include 'material/includes/material_js.html' %}
</html>

portal/templates/adminpanel/mail_sent.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div class="container">
	<h2>
		Startup request has been approved
	</h2>
</div>

</body>
</html>

portal/templates/adminpanel/startup_ranking.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Founder|Admin</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.min.css' %}">
	<style>
		#sortable1, #sortable2 {
			border: 1px solid #eee;
			min-width: 49%;
			height: 500px;
			list-style-type: none;
			margin: 3px;
			padding: 5px;
			float: left;
			overflow:scroll;
		}
		#sortable1 li, #sortable2 li {
			margin: 5px 5px 5px 5px;
			padding: 5px;
			font-size: 1.2em;
			min-width: 200px;
			border-radius: 7px;
		}
		#location{
			font-size:0.7em;
			margin-left: 75%;
		}
		.list-column{
			height: 550px
			padding: 10px;
		}
	</style>
	<script>
		$(function() {
			$( "#sortable1, #sortable2" ).sortable({
				connectWith: ".connectedSortable"
			}).disableSelection();
		});

	</script>
</head>
<body class="container grey lighten-3">
	<h1 class="flow-text center">
		STARTUP RANKING LIST
	</h1>
	<a href="/admin">Home</a>
	<div>
		<p>
			To publish Rank List/Trending Startups:
		</p>
		<ol>
			<li>
				Drag and drop Startups from the Left into the right box to set trending and ranks.
			</li>
			<li>
				Re-arrange the dropped startups on the right to set an ascending order of ranks. 
			</li>
			<li>
				To unpublish a previously ranked startup drag it from the right box into the left box.
			</li>
			<li>
				Click the "Publish" button to publish ranks.
			</li>
		</ol>
	</div>
	<div class="row list-column">	
		<ul id="sortable1" class="connectedSortable white z-depth-1">
			{% for s in u_startups %}
			<li class="grey lighten-4">
				<p id = "{{s.name_of_startup}}" class="bold">
					{{ s.name_of_startup }}
					<span class="condensed light right">{{s.location}}</span>
				</p>
			</li>
			{% endfor %}
		</ul>
		<ul id="sortable2" class="connectedSortable white z-depth-1">
			{% for s in r_startups %}
			<li class="grey lighten-4">
				<p id = "{{s.name_of_startup}}" class="Para">
					{{ s.name_of_startup }}
					<span class="condensed light right">{{s.location}}</span>
				</p>
			</li>
			{% endfor %}
		</ul>
	</div>
	<button id="publish" class="btn waves-effect right col s2 m2 l2">Publish</button>
</body>


<script type="text/javascript">
	//AJAX call for publishing.
	
	$("#publish").click(function(){

		var publish = [];

  		//New Startups which are going to be ranked.
  		var children = $("#sortable2").children();
  		for(var i = 0 ; i < children.length ; i++)
  		{
  			var para = "";
  			para = children[i];
  			publish[i] = $(para).find('p').attr("id");
  		}

  		var queryset = { 'publish_array' : publish};

  		$.ajax({
  			traditional : true,
  			async 		: true,
  			type 	 	: 'POST',
  			url 		: '/adminpanel/rank_list/',
  			datatype 	: 'json',
  			data 		: queryset,
  			success 	: function(){
  				alert("The rank list has been Published!");
  			},
  			error 	: function(response){
  				alert("An Error Occurred. Please report this.");
  			},	
  		});
  	});
  </script>
  </html>

portal/templates/adminpanel/startupdetails.html
<!DOCTYPE html>
<html>
<head>
	<title> {{startup.name_of_startup}}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<div class="row">


			<h2>
				Startup
			</h2>
			<div id="startup">
				
				<span class="startup_name">
					<span>
						Name :
						<span>
							{{startup.name_of_startup}} <br>
						</span>
					</span>	
				</span>

				<span class="trade">

					<span>
						Trade :
					</span>
					<span>
						{{startup.type_of_trade}} <br>
					</span>
				</span>

				<span class="description">
					<span>
						Description :
					</span>
					<span>
						{{startup.description}}<br>
					</span>
				</span>
				
				<span class="location">
					<span>
						Location :
					</span>
					<span>
						{{startup.location}}<br>
					</span>
				</span>

				<span class="team_size">
					<span>
						TeamSize :
					</span>
					<span>{{startup.team_size}}<br>
					</span>
				</span>
			</div>


			<h2>
				Founders
			</h2>
			<div id="founders">

				{% for user in users %}

					<span class="name">
						<span>
							Name :
						</span>
						<span>
							{{user.first_name}} {{user.last_name}}<br>
						</span>
					</span>
					
					<span class="email">
						<span>
							Email :
						</span>
						<span>
							{{user.email}}<br>
						</span>
					</span>

					<span class="about">
						<span>
							About:
						</span>
						<span>
						{{user.about}}<br>
						</span>
					</span>

					<span class="designation">
					<span>
						Designation
					</span>
					<span>
						{{user.designation}}<br>
					</span>
					</span>
			</div>
			{% endfor %}
			
		</div>
		{% if startup.approval_status == "Pending" %}
		
		<br>
		<br>
		<a href="/adminpanel/startups/approve/{{startup.name_of_startup}}">
			<button type="button" class="btn btn-default">
				Approve 
			</button>
		</a>
		{% endif %}

	</div>
	
</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous">
	
</script>
</html>

portal/templates/adminpanel/startuprequests.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title> Startup requests</title>

	<link rel="stylesheet" type="text/css" href="{% static 'adminpanel/css/startuprequest.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>

	<div id="container">

		<div class="row">

			<div class="col-md-5 startups" id="approved" >
				<h2>
					Approved
				</h2>
				<div id="approved">

					{% for startup in approved_startups %}
					<span class="span-text">
						<a href="/adminpanel/startups/{{startup.name_of_startup}}"> {{startup.name_of_startup}}</a><br>
					</span>
					{% endfor %}

				</div>

			</div>

			<div class="col-md-5 startups"  id="pending">
				<h2>
					Pending
				</h2>
				<div id="pending">

					{% for startup in pending_startups %}
					<span class="span-text">
						<a href="adminpanel/startups/{{startup.name_of_startup}}"> {{startup.name_of_startup}}</a><br>
					</span>
					{% endfor %}
					
				</div>

			</div>
		</div>

	</div>
</body>


</html>