portal/portal/urls.py
# Django imports
from django.conf.urls import include, url
from django.contrib import admin

# Function Imports(Views)


from users.views import *
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# from resources.views import ResourceHandler
from events.views import EventHandler, EventDetails

# Rest Framework Imports
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# Url Imports.
from users import urls as users_urls
from startups import urls as startup_urls
from posts import urls as post_urls
from events import urls as event_urls
from dashboard import urls as  dashboard_urls
from users.views import AddFounderfromForm
from startups.views import AddStartupfromForm

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # Rest Framework Urls
    url(r'^auth-api/'			, include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/' 	, views.obtain_auth_token),
    url(r'^docs/'				, include('rest_framework_swagger.urls')),

    # user urls
    url(r'^api/user/' 			, include(users_urls)),
    url(r'^api/events/' 		, include(event_urls)),
    url(r'^api/startups/' 		, include(startup_urls)),
    url(r'^api/posts/' 			, include(post_urls)),
    url(r'^dashboard/' 			, include(dashboard_urls)),

    url(r'^user/addfounder' 	, AddFounderfromForm, name='add_founder_from_form'),
    url(r'^startup/addstartup' 	, AddStartupfromForm, name='add_startup'),
    url(r'^approvalrequest/' 	, InApproval, name='in_approval')

]

urlpatterns = format_suffix_patterns(urlpatterns)

portal/posts/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from posts.views import *


urlpatterns = [
    url(r'posts_list/$'         , PostHandler.as_view() , name = 'posts-list'),
    url(r'edit_post/$'          , EditPost, name='edit-post'),
    url(r'news_feed/'           , NewsFeed, name='news_feed'),
    # url(r'influencer_feed/'   , InfluencerNewsFeed, name = 'influencer-news-feed'),
    url(r'comments/$'           , CommentHandler.as_view(), name='CommentHandler'),
    url(r'comment_edit/$'       , EditComment, name='editComment'),
    url(r'like_or_comment/$'    , liker_or_comments, name='likes_or_comments'),
    url(r'like_or_unlike/$'     , LikeorUnlike.as_view(), name='like_or_unlike'),
    url(r'myposts/$'            , MyPosts,  name='my_posts'),
    url(r'confession_post'		, ConfessionPostCreate, name='confession_posts'),
    url(r'confession_news_feed'	, ConfessionNewsFeed, name='confession_news_feed'),
    url(r'confession_upvote'	, ConfessionUpvoteorDownvote, name='confession_upvote_downvote')
    ]

portal/users/urls.py
# URL module imports from django.
from django.conf.urls import include, url
from .views import *


urlpatterns = [
    url(r'^user_details/', UserHandler.as_view(), name='userHandler'),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^addfounder/$', AddCoFounder.as_view(), name='add_founder'),
    url(r'^mentor_details/$', MentorHandler.as_view(), name='mentor_handler'),
    url(r'^mentorsearch/$', MentorSearch.as_view(), name='influencer_list'),
    url(r'^mentorslist', MentorsList, name='mentors_list'),
    url(r'^logout/$', Logout_User, name='logout'),
    url(r'^id_token/$', ReturnIdentityToken , name='IdentityToken'),
]

portal/users/models.py
# Django Related imports.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
import uuid

# Database models related imports.
from startups.models import startUp


# Model For Founder profiles
class MyUser(AbstractUser):
    designation = models.CharField(max_length=25, blank=True)
    image = models.URLField(max_length=250, blank=True, null=True)
    about = models.TextField(blank=True)
    linkedin_url = models.URLField(max_length=1000, blank=True)
    twitter_handle = models.URLField(max_length=1000, blank=True)
    facebook_url = models.URLField(max_length=500, blank=True)
    startup = models.ForeignKey(startUp, related_name='cofounders', null=True, blank=True)
    following_startup = models.ManyToManyField(startUp, symmetrical=False, related_name='following_company', blank=True)
    tagline = models.CharField(max_length=80, blank=True)
    skills = models.CharField(max_length=100, blank=True)


class Mentor(MyUser):
    company_name = models.CharField(max_length=75, blank=True)
    expertise = models.CharField(max_length=100, blank=True)
    past_experience = models.TextField(blank=True)
    mentoring_startup = models.ManyToManyField(startUp, related_name="mentors", blank=True)
    chat_password = models.CharField(max_length=8, null=True, blank=True)
    chat_user = models.CharField(max_length=50, null=True, blank=True)
    identity_token = models.CharField(max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = "mentor"

    def __str__(self):
        return str(self.username)


class Investor(MyUser):
    company_name = models.CharField(max_length=75, blank=True)
    expertise = models.CharField(max_length=100, blank=True)
    past_experience = models.TextField(blank=True)
    investing_startup = models.ManyToManyField(startUp, related_name="investors")

    class Meta:
        verbose_name = "investor"

    def __str__(self):
        return str(self.username)

portal/users/forms.py
# Django Related imports
from django import forms

# Model imports

from startups.models import startUp


class AddUserForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)
    email = forms.EmailField(required=True)
    image = forms.FileField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_handle = forms.URLField(required=False)
    startup = forms.ModelChoiceField(queryset=startUp.objects.all())
    add_another_founder = forms.BooleanField(required=False)
    about = forms.CharField(widget=forms.Textarea, required=False)

portal/users/views.py
#  Django Related imports

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.db.models import Q
from django.utils.crypto import get_random_string
import boto.ses 
import datetime
import traceback
from portal import boto_helper
from portal.settings import  user_images_file_path, CDN_DOMAIN

#  Rest Framework imports.
from rest_framework.response import Response
from rest_framework.authentication import Token
from rest_framework.decorators import authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework import status, views
from rest_framework.decorators import api_view
from rest_framework import generics

# layer imports
from .layer import generate_identity_token


#  Importing models
from .models import MyUser
from startups.models import startUp

# Importing serializers
from .serializers import *
from startups.serializers import StartUpSerializer

#  Form imports
from users.forms import AddUserForm

# Form imports
from users.forms import *

#  Miscellaneous Imports.
import subprocess , os


# CBV for User Login.
class Login(views.APIView):

    def post(self, request):

        try:
            assert 'username' in request.data
            assert 'password' in request.data
            
            email = request.data['username']
            password = request.data['password']
            nonce = request.data['nonce']
            username = MyUser.objects.get(email=email).username
            user = authenticate(username=username, password=password)
            if user is not None:

                login(request, user)

                # If token exists then get else create it for the user
                token = Token.objects.get_or_create(user = user)

                if type(token) == type((1,2)):
                    token_key = token[0].key
                else:
                    token_key = token.key

                try:
                    mentor = Mentor.objects.get(id=user.id)
                    user_id = str(user.id)
#                     if mentor.identity_token:
#                         pass
#                     else:

                    identityToken = generate_identity_token(email, nonce, mentor.image)
                    mentor.identity_token = identityToken
                    mentor.save()
                    serialized_mentor = MentorSerializer(mentor)
                    data = serialized_mentor.data
                    data['auth_token'] = token_key
                    data['chat_password'] = mentor.chat_password
                    data['chat_user'] = mentor.chat_user
                    # data['identity_token'] = identityToken
                    return Response({
                        'success'       : True,
                        'mentor'        : data,
                        'status_code'   : status.HTTP_200_OK
                        })

                except Mentor.DoesNotExist:
                    startup = user.startup
                    startup_id = str(startup.id)
#                     if startup.identity_token:
#                         pass
#                     else:
                    identityToken = generate_identity_token(startup.name_of_startup, nonce, startup.startup_logo)
                    startup.identity_token = identityToken
                    startup.save()
                    serialized_user = UserloginSerializer(user)
                    serialized_cofounders = StartUpSerializer(startup)
                    data = serialized_cofounders.data
                    data['auth_token'] = token_key

                    return Response({
                        'success': True,
                        # 'auth_token'    : token_key,
                        'startup': data,
                        'status_code': status.HTTP_200_OK,
                        })
            else:
                    user = None
                    token_key = None
                    return Response({
                    'success'       : False,
                    'auth_token'    : token_key,
                    'user'          : user,
                    'error'         : 'Username or password invalid',
                    'status_code' : status.HTTP_400_BAD_REQUEST
                    }, status.HTTP_400_BAD_REQUEST)

        except MyUser.DoesNotExist:
            user = None
            token_key = None
            return Response({
            'success': False,
            'auth_token': token_key,
            'user': user,
            'error': 'No such user exists',
            'status': status.HTTP_404_NOT_FOUND,
            }, status.HTTP_404_NOT_FOUND)

        except AssertionError  as e:
            return Response({
                'error' : 'parameter not recieved',
                'status_code'   : status.HTTP_400_BAD_REQUEST
                }, status.HTTP_400_BAD_REQUEST)

        except Exception as e:
            err = repr(e)
            return Response({
                'success':False,
                'error': err,
                'status_code': status.HTTP_500_INTERNAL_SERVER_ERROR,
                }, status.HTTP_500_INTERNAL_SERVER_ERROR)


@authentication_classes((TokenAuthentication,))
@api_view(["POST"])
def ReturnIdentityToken(request):
    try:
        assert request.data["nonce"]
        nonce_string = request.data["nonce"]
        try:
            mentor = Mentor.objects.get(id=request.user.id)
            user_id = str(request.user.id)

            identityToken = generate_identity_token(request.user.email, nonce_string, mentor.image)
            mentor.identity_token = identityToken
            mentor.save()
            return Response({
                'success'       : True,
                'identity_token': identityToken,
                'status_code'   : status.HTTP_200_OK
            })

        except Mentor.DoesNotExist:
            startup = request.user.startup
            startup_id = str(startup.id)
            identityToken = generate_identity_token(startup.name_of_startup, nonce_string, startup.startup_logo)
            startup.identity_token = identityToken
            startup.save()
            return Response({
                'success': True,
                'identity_token': identityToken,
                'status_code': status.HTTP_200_OK,
            })
    except MyUser.DoesNotExist:
        user = None
        token_key = None
        return Response({
            'success'       : False,
            'auth_token'    : token_key,
            'user'          : user,
            'error'         : 'No such user exists',
            'status'        : status.HTTP_404_NOT_FOUND,
        }, status.HTTP_404_NOT_FOUND)

    except AssertionError  as e:
        return Response({
            'error': 'parameter not recieved',
            'status_code': status.HTTP_400_BAD_REQUEST
        }, status.HTTP_400_BAD_REQUEST)

    except Exception as e:
        err = repr(e)
        return Response({
            'success':False,
            'error': err,
            'status_code': status.HTTP_500_INTERNAL_SERVER_ERROR,
        }, status.HTTP_500_INTERNAL_SERVER_ERROR)

 
# CBV for adding cofounder via App
class AddCoFounder(views.APIView):

    @authentication_classes((TokenAuthentication,))
    @permission_classes((IsAuthenticated,))
    def post(self, request):
        try:
            assert 'email' in request.data
            email = request.data['email']

            # finding the current user
            current_user = request.user
            # selecting the  current startup 
            startup = current_user.startup

            # connecting to boto using  key_id and access_key
            conn = boto.ses.connect_to_region(
                    'us-west-2',
                    aws_access_key_id='AKIAJDC3JOCQK3LCVTHA',
                    aws_secret_access_key='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')

            # setting email as username and email and startup for the cofounder
            user = MyUser.objects.create(email=email, username=email,startup=startup)
            # Generating a random 8_length token string
            invite_token = get_random_string(length=8)
            # setting the invite token as password
            user.set_password(invite_token)
            user.save()

            html = '<html><head><title>Approved</title><head><body> ' + \
                   '<div><p>Hello your request for Founders has been approved.' + \
                   'Below are your attached username and password <br> username : ' + \
                   email + '<br> password : ' + invite_token + '<br>' + \
                   'You can now login to the app <br><br>Regards<br>Founder</body></html>'

            # sending the mail
            try:
                conn.send_email(
                    'karan@grappus.com',
                    'Request Approved',
                    None,
                    [email],
                    format='html',
                    html_body=html,
                  )
                return Response({
                            'success'   : True ,
                            'msg'       : 'mail sent to cofounder',
                            'status'    : status.HTTP_200_OK,
                            })
            except Exception as e:
                err = repr(e)
                MyUser.objects.filter(email = email).delete()
                return Response({
                'error': err,
                'status': status.HTTP_400_BAD_REQUEST,
                })
        except AssertionError:
            return Response({
                'error': 'email not recieved'
                })
        except Exception as e:
                err = repr(e)
                return Response({
                'error' : err,
                'status' : status.HTTP_400_BAD_REQUEST,
                })


# CBV for User Related Queries

portal/users/templates/users/addfounders.html
<!DOCTYPE html>
{% load material_form %}
{% load staticfiles %}
<html>
<head>

    <title>Add Founder</title>

    <meta charset="utf-8">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'users/addfounder.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'materialize/css/materialize.css' %}"> -->


    <script type="text/javascript">


        function handleFileSelect() {
            var files = $('#id_image')[0].files;

    // Loop through the FileList and render image files as thumbnails.
    for (var i = 0, f; f = files[i]; i++) {

      // Only process image files.
      if (!f.type.match('image.*')) {
        continue;
      }

      var reader = new FileReader();

      // Closure to capture the file information.
      reader.onload = (function(theFile) {
        
        return function(e) {
          // Render thumbnail.
          var span = document.createElement('span');
          span.innerHTML = 
          [

          '<img style="height: 75px;  margin: 5px" src="', 
          e.target.result,
          '" title="', escape(theFile.name), 
          '"/>'
          ].join('');
          $('#list').show();
          document.getElementById('list').insertBefore(span, null);
      };
  })(f);

      // Read in the image file as a data URL.
      reader.readAsDataURL(f);
  }
}




    </script>
</head>

<body>


<div class="container">

    <div class="form ">
        <div class="form-heading">
            <img class="img-header" src="{% static 'images/f_logo.png' %}" height="200px" width="200px"><br>
            <h2>
                Add Founder
            </h2>
        </div>
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}


            <div id="firstName" class=" row form-element">
                <label id="label_first_name"> First Name</label> <span class="required">*</span>
                <div class="input">
                    <input type="text" id="id_first_name" name="first_name">
                </div>

                {{form.first_name.errors}}
            </div>
            <div id="lastName" class=" row form-element">
                <label>Last Name</label>
                <div class="input">
                    <input type="text" id="id_last_name" name="last_name">
                </div>

                {{form.last_name.errors}}
            </div>
            <div id="email" class=" row form-element">
                <label>Email</label> <span class="required">*</span>
                <div class="input">
                    <input type="text" id="id_email" name="email">
                </div>

                {{form.email.errors}}
            </div>
            <div id="image" class="row form-element">
                <label>Image</label> <span class="required">*</span>
                <div>
                    <input id="id_image" name="image" class="custom-file-input" type="file"
                           onchange="handleFileSelect()">

                    <output id="list"></output>
                </div>

                {{form.image.errors}}
            </div>
            <div id="linkedin" class="row form-element">
                <label>Linkedin Url</label>
                <div class="input">
                    <input type="url" id="id_linkedin_url" name="linkedin_url" placeholder="Use https"/>
                </div>
                {{form.linkedin_url.errors}}
            </div>
            <div id="facebook" class="row form-element">
                <label>Facebook Url</label>
                <div class="input">
                    <input type="url" id="id_facebook_url" name="facebook_url" placeholder="Use https"/>
                </div>
                {{form.facebook_url.errors}}
            </div>

            <div id="twitter" class="row form-element">
                <label>Twitter Handle</label>
                <div class="input">
                    <input type="url" id="id_twitter_handle" name="twitter_handle" placeholder="Use https"/>
                </div>
                {{form.titter_handle.errors}}
            </div>
            <div id="startup" class="row form-element">
                <label>Startup</label> <span class="required">*</span>
                <div>
                    {{form.startup}}
                    <!-- <select name="startup" id="id_startup">
                        <option>
                            Choose Startup
                        </option>
                        {% for startup in form.startup.field.queryset%}
                        <option>
                            {{startup}}
                        </option>
                        {% endfor %}
                    </select> -->
                </div>

                {{form.startup.errors}}
            </div>

            <div id="about" class="row form-element">
                <label>About</label>
                <div class="input">
                    <textarea rows="5" id="id_about" name="about"></textarea>

                    {{form.about.errors}}
                </div>
            </div>

            <div id="add_founder" class="row form-element">
                <label>Add Another founder</label>
                <div id="add_another_founder_checkbox">
                    <input id="id_add_another_founder" name="add_another_founder" type="checkbox">
                </div>
            </div>
            <div id="buttons" class="row form-element">
                <input type="submit" value="Save " class="btn btn-submit" id="save"/>
                <input type="submit" value="Add Another Founder " class="btn right submit" id="add"/>
            </div>

        </form>
    </div>
    <div class="footer">

    </div>

</div>

</body>
<script type="text/javascript">
	$(function(){
		$(':checkbox').change(function() {

			if ($('#id_add_another_founder').is(':checked')) {
				$('#add').show();
				$('#save').hide();
			}
			else {
				$('#add').hide();
				$('#save').show();
			}
		});
	});


</script>

<!--
<script type="text/javascript">
	$( "#id_facebook_url" ).val('https://' );
	$( "#id_linkedin_url" ).val('https://' );
	$( "#id_twitter_handle" ).val('https://' );
</script>-->

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>
</html>

portal/users/templates/users/inapproval.html
<!DOCTYPE html>
<html>
<head>
	<title>Request in Approval</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

</head>
<body>
	<div class="container">
		<div class="row">
			<h1>
				Thank you for filling out the details. Your request has been accepted and will be <br>
				reviewed by the moderators.<br>
				You will recieve an email once your request has been approved
			</h1>
		</div>
	</div>
</body>
</html>

portal/users/templates/users/mail_sent.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div class="container">
	<h2>
		Startup request has been approved
	</h2>
</div>

</body>
</html>