portal/portal/urls.py
# Django imports
from django.conf.urls import include, url
from django.contrib import admin

# Function Imports(Views)


from users.views import *
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# from resources.views import ResourceHandler
from events.views import EventHandler, EventDetails

# Rest Framework Imports
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# Url Imports.
from users import urls as users_urls
from startups import urls as startup_urls
from posts import urls as post_urls
from events import urls as event_urls
from dashboard import urls as  dashboard_urls
from users.views import AddFounderfromForm
from startups.views import AddStartupfromForm

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # Rest Framework Urls
    url(r'^auth-api/'			, include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/' 	, views.obtain_auth_token),
    url(r'^docs/'				, include('rest_framework_swagger.urls')),

    # user urls
    url(r'^api/user/' 			, include(users_urls)),
    url(r'^api/events/' 		, include(event_urls)),
    url(r'^api/startups/' 		, include(startup_urls)),
    url(r'^api/posts/' 			, include(post_urls)),
    url(r'^dashboard/' 			, include(dashboard_urls)),

    url(r'^user/addfounder' 	, AddFounderfromForm, name='add_founder_from_form'),
    url(r'^startup/addstartup' 	, AddStartupfromForm, name='add_startup'),
    url(r'^approvalrequest/' 	, InApproval, name='in_approval')

]

urlpatterns = format_suffix_patterns(urlpatterns)

portal/posts/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from posts.views import *


urlpatterns = [
    url(r'posts_list/$'         , PostHandler.as_view() , name = 'posts-list'),
    url(r'edit_post/$'          , EditPost, name='edit-post'),
    url(r'news_feed/'           , NewsFeed, name='news_feed'),
    # url(r'influencer_feed/'   , InfluencerNewsFeed, name = 'influencer-news-feed'),
    url(r'comments/$'           , CommentHandler.as_view(), name='CommentHandler'),
    url(r'comment_edit/$'       , EditComment, name='editComment'),
    url(r'like_or_comment/$'    , liker_or_comments, name='likes_or_comments'),
    url(r'like_or_unlike/$'     , LikeorUnlike.as_view(), name='like_or_unlike'),
    url(r'myposts/$'            , MyPosts,  name='my_posts'),
    url(r'confession_post'		, ConfessionPostCreate, name='confession_posts'),
    url(r'confession_news_feed'	, ConfessionNewsFeed, name='confession_news_feed'),
    url(r'confession_upvote'	, ConfessionUpvoteorDownvote, name='confession_upvote_downvote')
    ]

portal/startups/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from .views import *


urlpatterns = [
    url(r'^startup_edit/$', StartUpHandler.as_view(), name='edit_startup'),
    url(r'^rank_list/$', StartUpRankList, name='startup_ranklist'),
    url(r'^follow/$', FollowCompany.as_view(), name='follow_relations'),
    url(r'^startup_details/$', StartUpDetails, name='startup_details'),
    url(r'^startupsearch/$',StartUpSearch.as_view(), name='startup_search'),
    url(r'^startupslist', StartupList, name='startups_list')

]

portal/startups/models.py
# Django related imports
from django.db import models


class startUp(models.Model):
    APPROVAL_STATUS_CHOICES = (
        (0, 'Pending'),
        (1, 'Approved')
    )
    TEAM_SIZE = (
        ('None', 'None'),
        ('0-10', '0-10'),
        ('10+', '10+'),
        ('20+', '20+'),
        ('30+', '30+'),
        ('40+', '40+'),
        ('50+', '50+')
    )
    TYPE_OF_TRADE = (
        ('None', 'None'),
        ('Technology', 'Technology'),
        ('Logistics', 'Logistics'),
        ('Marketing', 'Marketing'),
        ('Ecommerce', 'Ecommerce'),
        ('Services', 'Services')
    )
    # Choices will be added soon.

    name_of_startup = models.CharField('Registered name of StartUp', max_length=100, unique=True)
    background_startup_image = models.URLField(max_length=250, blank=True, null=True)
    startup_logo = models.URLField(max_length=250, blank=True, null=True)
    company_website = models.URLField(max_length=50, blank=True, null=True)
    linkedin_url = models.URLField(max_length=1000, blank=True)
    facebook_url = models.URLField(max_length=1000, blank=True)
    twitter_handle = models.URLField(max_length=1000, blank=True)
    type_of_trade = models.CharField(choices=TYPE_OF_TRADE, max_length=100, blank=True)
    inc_year = models.CharField(max_length=4,null=True, blank=True)
    description = models.TextField(null=True)
    team_size = models.CharField(choices=TEAM_SIZE, max_length=10, null=True, blank=True)
    location = models.CharField(max_length=250, null=True, blank=True)
    trending = models.NullBooleanField(default=False)
    rank = models.IntegerField(default=0, blank=True)
    approval_status = models.PositiveIntegerField(choices=APPROVAL_STATUS_CHOICES, default=0)
    company_tagline = models.CharField(max_length=200, blank=True)
    trending_reason = models.CharField(max_length=200, blank=True, null=True)
    chat_password = models.CharField(max_length=8, null=True, blank=True)
    chat_user = models.CharField(max_length=50, null=True, blank=True)
    identity_token = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.name_of_startup

portal/startups/forms.py
#Django Related imports
from django import forms
from django.forms import ModelForm

#Model imports

from .models import startUp



class AddStartupForm(forms.Form):
    TEAM_SIZE = (
        ('None', 'None'),
        ('0-10', '0-10'),
        ('10+', '10+'),
        ('20+', '20+'),
        ('30+', '30+'),
        ('40+', '40+'),
        ('50+', '50+')
    )
    TYPE_OF_TRADE = (
        ('None', 'None'),
        ('Technology', 'Technology'),
        ('Logistics', 'Logistics'),
        ('Marketing', 'Marketing'),
        ('Ecommerce', 'Ecommerce'),
        ('Services', 'Services')
    )

    name_of_startup      = forms.CharField(max_length= 100, label = 'Name of Startup', required = True)
    startup_logo         = forms.ImageField(required = False)
    linkedin_url         = forms.URLField(required=False)
    facebook_url         = forms.URLField(required=False)
    company_website      = forms.URLField(required=True)
    twitter_handle       = forms.CharField(max_length=50, required=False)
    inc_year             = forms.IntegerField(required = True)
    type_of_trade        = forms.ChoiceField(choices=TYPE_OF_TRADE,widget = forms.Select(), required = True)
    description          = forms.CharField(widget=forms.Textarea,required = True)
    team_size            = forms.ChoiceField(choices=TEAM_SIZE, widget = forms.Select(), required = False)
    location             = forms.CharField(max_length=200, required = True)
    company_tagline      = forms.CharField(max_length=100, required = False)

portal/users/forms.py
# Django Related imports
from django import forms

# Model imports

from startups.models import startUp


class AddUserForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)
    email = forms.EmailField(required=True)
    image = forms.FileField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_handle = forms.URLField(required=False)
    startup = forms.ModelChoiceField(queryset=startUp.objects.all())
    add_another_founder = forms.BooleanField(required=False)
    about = forms.CharField(widget=forms.Textarea, required=False)

portal/startups/views.py
# Django related imports

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.crypto import get_random_string

from portal import boto_helper
from portal.settings import startup_images_file_path, CDN_DOMAIN
import datetime
import os
import traceback
from django.db.models import Q

# Rest Framework Imports.
from rest_framework.authentication import  TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.decorators import authentication_classes, permission_classes, api_view
from rest_framework.views import APIView
from rest_framework import status, views
from rest_framework import filters
from rest_framework import generics

# Database model related imports.
from users.models import MyUser
from .models import startUp

# Serializer class Imports.
from .serializers import *
from users.serializers import *

# Form Imports
from startups.forms import *


class StartUpHandler(APIView):

    @authentication_classes((TokenAuthentication,))
    @permission_classes((IsAuthenticated,))
    def post(self, request):

        file_path = startup_images_file_path

        try:
            user = request.user
            s_id = request.data['id']
            Startup = startUp.objects.get(id=s_id)

            if user in Startup.cofounders.all():

                # if request.data['company_tagline']:
                #     a = request.data['company_tagline'].split(' ')[0:5]
                #     company_tagline = ' '.join(a)
                #     request.data['company_tagline'] = company_tagline

                if request.FILES.get('startup_logo'):
                    try:
                        startup_logo = request.FILES.get('startup_logo')
                        file_name = 'sl_' + str(startup_logo)
                        image_file = open(os.path.join(file_path, file_name), 'wb')
                        image_file.write(startup_logo.read())
                        image_file.close()
                        startup_logo_path = boto_helper.upload_image(file_path, file_name)
                        startup_logo_s3 = "https://" + CDN_DOMAIN + "/" + file_name
                        request.data['startup_logo'] = startup_logo_s3
                        Startup.startup_logo = startup_logo_s3
                        Startup.save()

                    except Exception as e:
                        err = repr(e)

                        return Response({
                            "success": False,
                            "error": err,
                            "status": status.HTTP_500_INTERNAL_SERVER_ERROR,
                        }, status.HTTP_500_INTERNAL_SERVER_ERROR)

                startup_edited = StartupEditSerializer(Startup, data=request.data)
                if startup_edited.is_valid():
                    startup_edited.save()
                    startup_edited = StartupEditedSerializer(Startup)

                    return Response({
                        'success': True,
                        'message': 'Data successfully edited',
                        'startup': startup_edited.data,
                        'status': status.HTTP_200_OK,
                    })
                else:
                    return Response({
                        'success': False,
                        'error': 'Serializer data is invalid.',
                        'serialized_data': startup_edited.data,
                        'serializer_errors': startup_edited.errors,
                        'status': status.HTTP_400_BAD_REQUEST,
                    }, status.HTTP_400_BAD_REQUEST)

            else:
                return Response({
                    'success': False,
                    'error': 'Cannot edit this Startup, not a cofounder ',
                    'status': status.HTTP_403_FORBIDDEN
                }, status.HTTP_403_FORBIDDEN)

        except startUp.DoesNotExist:
            return Response({
                'success': False,
                'error': 'No startup found. ',
                'status': status.HTTP_404_NOT_FOUND,
            }, status.HTTP_404_NOT_FOUND)
        except AssertionError:
            return Response({
                'success': False,
                'error': 'Parameter Error startup_id Not provided',
                'status': status.HTTP_400_BAD_REQUEST,
            }, status.HTTP_400_BAD_REQUEST)

        except Exception as e:
            err = repr(e)
            return Response({
                'success': False,
                'error': err,
                'status': status.HTTP_500_INTERNAL_SERVER_ERROR,
            }, status.HTTP_500_INTERNAL_SERVER_ERROR)


class StartUpSearch(generics.ListAPIView):

    @authentication_classes((TokenAuthentication,))
    @permission_classes((IsAuthenticated,))
    def get(self, request):

        user = request.user
        startup_name = self.request.query_params.get('startup_name', None)
        view_all = request.GET.get('view_all')
        view_all = int(view_all)

        if startup_name is not None:
            if view_all:
                queryset = startUp.objects.filter(Q(name_of_startup__icontains=startup_name),
                                                  Q(approval_status=1))
                serialized_startups = StartUpSerializerFields(queryset, many=True)
                i = 0
                data = serialized_startups.data

                for current_startup in data:
                    startup = startUp.objects.get(name_of_startup=current_startup['name_of_startup'])

                    if user in startup.cofounders.all():
                        data[i]['own_startup'] = True
                    else:
                        data[i]['own_startup'] = False

                    if user.startup:

                        if user in startup.following_company.all():
                            data[i]['followed'] = True
                        else:
                            data[i]['followed'] = False
                    else:
                        if user in user.following_startup.all():
                            data[i]['followed'] = True
                        else:
                            data[i]['followed'] = False
                    i = i + 1

                return Response({
                    'success': True,
                    'startups': data,
                    'status': status.HTTP_200_OK,
                })
            else:
                queryset = startUp.objects.filter(Q(name_of_startup__icontains=startup_name),
                                                  Q(approval_status=1))[0:10]
                serialized_startups = StartUpSerializerFields(queryset, many=True)

                i = 0
                data = serialized_startups.data
                for current_startup in data:
                    startup = startUp.objects.get(name_of_startup=current_startup['name_of_startup'])

                    if user in startup.cofounders.all():
                        data[i]['own_startup'] = True
                    else:
                        data[i]['own_startup'] = False

                    if user.startup:

                        if user in startup.following_company.all():
                            data[i]['followed'] = True
                        else:
                            data[i]['followed'] = False
                    else:
                        if user in user.following_startup.all():
                            data[i]['followed'] = True
                        else:
                            data[i]['followed'] = False
                    i = i + 1
                return Response({
                    'success': True,
                    'startups': data,
                    'status': status.HTTP_200_OK,
                })
        else:
            return Response({
                'sucess': False,
                'error': 'No name specified',
                'status': status.HTTP_400_BAD_REQUEST,
            }, status.HTTP_400_BAD_REQUEST)


# Endpoint for StartUp Details
@authentication_classes((TokenAuthentication,))
@api_view(['GET'])
def StartUpDetails(request):

    try:

        s_id = request.GET.get('id')
        assert s_id
        startup = startUp.objects.get(id=s_id)
        serialized_data_startups = StartUpSerializer(startup, context={'request': request})
        return Response({
            'success': True,
            'startup': serialized_data_startups.data,
            'status_code': status.HTTP_200_OK
        })

    except startUp.DoesNotExist:
        return Response({
            'success': False,
            'error': 'No such startup found.',
            'status_code': status.HTTP_404_NOT_FOUND,
        }, status.HTTP_404_NOT_FOUND)
    except AssertionError:
        return Response({
            'status': status.HTTP_400_BAD_REQUEST,
            'success': False,
            'error': 'Please Check parameters.'
        }, status.HTTP_400_BAD_REQUEST)


@authentication_classes((TokenAuthentication,))
@permission_classes((IsAuthenticated,))
@api_view(['GET'])
def StartupList(request):
    startups = startUp.objects.filter(approval_status=1)
    serialzed_startups = StartUpSerializerFields(startups, many=True)
    return Response({
        'status': status.HTTP_200_OK,
        'success': True,
        'startups': serialzed_startups.data
    }, status.HTTP_200_OK)


# View for following startups.
class FollowCompany(APIView):
    @authentication_classes((TokenAuthentication,))
    @csrf_exempt
    def post(self, request):
        try:
            assert request.data["follow"]
            if int(request.data['follow']):
                try:
                    assert 'id' in request.data
                    s_id = request.data['id']
                    assert s_id != ''
                    startup = startUp.objects.get(id=s_id)

portal/startups/templates/startup/addstartup.html
<!DOCTYPE html>
{% load material_form %}
{% load staticfiles %}
<html>
<head>

	<title>Add Startup</title>

	<meta charset="utf-8">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{%static 'startups/css/addstartup.css' %}">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	
	<script type="text/javascript">
		


		function exchange(e){
			$('#'+e).children()[1].children[0].focus();
			
		}
		$(function(){
			$('#id_company_tagline').keyup(function(){

				var temp = $('#id_company_tagline').val();
				var temp = temp.split(' ');
				if (temp.length>5)
				{
					$('#tagline_error').show();

					setTimeout(function(){
						$('#id_company_tagline').focus();},1000);
				}
				if (temp.length<=5){
					$('#tagline_error').hide();
				}
			});
		});

		$(function(){


			$(':checkbox').change(function() {

				if ($('#id_add_another_founder').is(':checked')) {
					$('#add').show();
					$('#save').hide();
				}
				else {
					$('#add').hide();
					$('#save').show();
				}
			});

		});
	</script>
</head>

<body>
	
	
	<div class="container">	
		<nav class="navbar navbar-default">

			<div class="navbar-header">
				<span class="navbar-brand">
					Founders
				</span>
			</div>
		</nav>
		<div class="form">
			<form  enctype="multipart/form-data" method="POST" action="">
				{% csrf_token %}

				

				<div id="name_of_startup" class=" row form-element" onmouseover="exchange(id)">
					<label id="label_name_of_startup"> Name of Startup</label>
					<div class="input"  >
						<input type="text"  id="id_name_of_startup" name="name_of_startup" tabindex="1">
						<div class="errors">
							{{form.name_of_startup.errors}}
						</div>
					</div>
				</div>
				<div id="background_startup_image" class="row form-element" onmouseover="exchange(id)">
					<label>Background Startup Image</label>
					<div>
						<input id="id_background_startup_image"  class="filestyle" data-classButton="btn btn-default" name="background_startup_image" type="file">
						<div class="errors">
							{{form.background_startup_image.errors}}
						</div>
					</div>
				</div>
				<div id="startup_logo" class="row form-element" onmouseover="exchange(id)">
					<label>Startup Logo</label>
					<div>
						<input id="id_startup_logo"  class="filestyle" data-classButton="btn btn-default" name="startup_logo" type="file">
						<div class="errors">
							{{form.startup_logo.errors}}
						</div>
					</div>
				</div>
				
				<div id="company_website" class="row form-element" onmouseover="exchange(id)">
					<label>Company Website</label>
					<div  class="input">
						<input type = "url" id="id_company_website" name="company_website">
						<div class="errors">
							{{form.company_website.errors}}
						</div>
					</div>
				</div>
				<div id="linkedin" class="row form-element" onmouseover="exchange(id)">
					<label>Linkedin Url</label>
					<div  class="input">
						<input type="url" id="id_linkedin_url" name="linkedin_url" />
						<div class="errors">
							{{form.linkedin_url.errors}}
						</div>
					</div>
				</div>
				<div id="facebook" class="row form-element" onmouseover="exchange(id)">
					<label>Facebook Url</label>
					<div  class="input">
						<input type = "url" id="id_facebook_url" name="facebook_url">
						<div class="errors">
							{{form.facebook_url.errors}}
						</div>
					</div>
				</div>
				
				<div id="twitter" class="row form-element" onmouseover="exchange(id)">
					<label>Twitter Handle</label>
					<div class="input">
						<input type="url" id="id_twitter_handle" name="twitter_handle">
						<div class="errors">
							{{form.twitter_handle.errors}}
						</div>
					</div>
				</div>
				<div id="description" class="row form-element"  onmouseover="exchange(id)">
					<label>Description</label>
					<div class="input">
						<textarea rows="4"  cols="60" id="id_description" name="description"></textarea>
						<div class="errors">
							{{form.description.errors}}
						</div>
					</div>	
				</div>

				<div id="location" class="row form-element" onmouseover="exchange(id)">
					<label>Location</label>
					<div class="input">
						<input type="text" name="location" id="id_location">
						<div class="errors">
							{{form.location.errors}}
						</div>
					</div>
				</div>

				<div id="inc_year" class="row form-element" onmouseover="exchange(id)">
					<label>Inc Year</label>
					<div class="input">
						<input type="text" name="inc_year" id="id_inc_year">
						<div class="errors">
							{{form.inc_year.errors}}
						</div>
					</div>
				</div>
				<div id="team_size" class="row form-element" onmouseover="exchange(id)">
					<label>Team Size</label>
					<div class="input">
						<input type="text" name="team_size" id="id_team_size">
						<div class="errors">
							{{form.team_size.errors}}
						</div>
					</div>
				</div>
				<div id="type_of_trade" class="row form-element" onmouseover="exchange(id)">
					
					<label>Type of Trade</label>
					<div>
						{{form.type_of_trade}}
						{{form.type_of_trade.errors}}
					</div>

				</div>
				<div id="company_tagline" class="row form-element" onmouseover="exchange(id)">
					<label>Company Tgaline</label>
					<div class="input">
						<input type="text" name="company_tagline" id="id_company_tagline">
						<div  id="tagline_error">
							your tagline is greater than five
						</div>
						<div class="errors">
							{{form.tagline.errors}}
						</div>
					</div>
				</div>

				<div class="row form-element" >
					<input type="submit" value="Save " class="btn btn-submit"  id="save"  />
				</div>	
				
			</form>
		</div>
		
	</div> 

</body>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>