portal/dashboard/urls.py
# Django imports
from django.conf.urls import include, url
from .views import *

urlpatterns = {
    url(r'^$', dashboard, name='dashboard'),
    url(r'^login/$', Login, name='login'),
    url(r'^logout/$', Logout, name='logout'),
    url(r'^startuprequests/(?P<page_no>\w+)$', StartupRequests, name='startup_request'),
    url(r'^approve/(?P<startup_name>\w+)/$', StartupApprove, name='startup_approved'),
    url(r'^startupranklist/$', StartupRank, name='startup_rank'),
    url(r'^startups/(?P<page_no>\w+)', ViewStartups, name='view_startups'),
    url(r'^addevent/$', AddEvent, name='addevent'),
    url(r'^posts/(?P<page_no>\w+)', ViewPosts, name='view_posts'),
    url(r'^events/(?P<page_no>\w+)', ViewEvents, name='view_ecents'),
    url(r'^addevent', AddEvent, name='add_event'),
    url(r'^addstartup', AddStartup, name='add_startup'),
    url(r'^addfounder', AddFounder, name='add_founder'),
    url(r'^addmentor', AddMentor, name='add_founder'),
    url(r'^mentors/(?P<page_no>\w+)', ViewMentors, name='view_mentors'),
    url(r'^confessions/(?P<page_no>\w+)', ViewConfessions, name='view_mentors'),

}

portal/portal/urls.py
# Django imports
from django.conf.urls import include, url
from django.contrib import admin

# Function Imports(Views)


from users.views import *
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# from resources.views import ResourceHandler
from events.views import EventHandler, EventDetails

# Rest Framework Imports
from rest_framework.authtoken import views
from rest_framework.urlpatterns import format_suffix_patterns

# Url Imports.
from users import urls as users_urls
from startups import urls as startup_urls
from posts import urls as post_urls
from events import urls as event_urls
from dashboard import urls as  dashboard_urls
from users.views import AddFounderfromForm
from startups.views import AddStartupfromForm

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # Rest Framework Urls
    url(r'^auth-api/'			, include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^api-token-auth/' 	, views.obtain_auth_token),
    url(r'^docs/'				, include('rest_framework_swagger.urls')),

    # user urls
    url(r'^api/user/' 			, include(users_urls)),
    url(r'^api/events/' 		, include(event_urls)),
    url(r'^api/startups/' 		, include(startup_urls)),
    url(r'^api/posts/' 			, include(post_urls)),
    url(r'^dashboard/' 			, include(dashboard_urls)),

    url(r'^user/addfounder' 	, AddFounderfromForm, name='add_founder_from_form'),
    url(r'^startup/addstartup' 	, AddStartupfromForm, name='add_startup'),
    url(r'^approvalrequest/' 	, InApproval, name='in_approval')

]

urlpatterns = format_suffix_patterns(urlpatterns)

portal/posts/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from posts.views import *


urlpatterns = [
    url(r'posts_list/$'         , PostHandler.as_view() , name = 'posts-list'),
    url(r'edit_post/$'          , EditPost, name='edit-post'),
    url(r'news_feed/'           , NewsFeed, name='news_feed'),
    # url(r'influencer_feed/'   , InfluencerNewsFeed, name = 'influencer-news-feed'),
    url(r'comments/$'           , CommentHandler.as_view(), name='CommentHandler'),
    url(r'comment_edit/$'       , EditComment, name='editComment'),
    url(r'like_or_comment/$'    , liker_or_comments, name='likes_or_comments'),
    url(r'like_or_unlike/$'     , LikeorUnlike.as_view(), name='like_or_unlike'),
    url(r'myposts/$'            , MyPosts,  name='my_posts'),
    url(r'confession_post'		, ConfessionPostCreate, name='confession_posts'),
    url(r'confession_news_feed'	, ConfessionNewsFeed, name='confession_news_feed'),
    url(r'confession_upvote'	, ConfessionUpvoteorDownvote, name='confession_upvote_downvote')
    ]

portal/startups/urls.py
#URL module imports from django.
from django.conf.urls import include, url
from .views import *


urlpatterns = [
    url(r'^startup_edit/$', StartUpHandler.as_view(), name='edit_startup'),
    url(r'^rank_list/$', StartUpRankList, name='startup_ranklist'),
    url(r'^follow/$', FollowCompany.as_view(), name='follow_relations'),
    url(r'^startup_details/$', StartUpDetails, name='startup_details'),
    url(r'^startupsearch/$',StartUpSearch.as_view(), name='startup_search'),
    url(r'^startupslist', StartupList, name='startups_list')

]

portal/dashboard/models.py
from django.db import models

# Create your models here.

portal/startups/models.py
# Django related imports
from django.db import models


class startUp(models.Model):
    APPROVAL_STATUS_CHOICES = (
        (0, 'Pending'),
        (1, 'Approved')
    )
    TEAM_SIZE = (
        ('None', 'None'),
        ('0-10', '0-10'),
        ('10+', '10+'),
        ('20+', '20+'),
        ('30+', '30+'),
        ('40+', '40+'),
        ('50+', '50+')
    )
    TYPE_OF_TRADE = (
        ('None', 'None'),
        ('Technology', 'Technology'),
        ('Logistics', 'Logistics'),
        ('Marketing', 'Marketing'),
        ('Ecommerce', 'Ecommerce'),
        ('Services', 'Services')
    )
    # Choices will be added soon.

    name_of_startup = models.CharField('Registered name of StartUp', max_length=100, unique=True)
    background_startup_image = models.URLField(max_length=250, blank=True, null=True)
    startup_logo = models.URLField(max_length=250, blank=True, null=True)
    company_website = models.URLField(max_length=50, blank=True, null=True)
    linkedin_url = models.URLField(max_length=1000, blank=True)
    facebook_url = models.URLField(max_length=1000, blank=True)
    twitter_handle = models.URLField(max_length=1000, blank=True)
    type_of_trade = models.CharField(choices=TYPE_OF_TRADE, max_length=100, blank=True)
    inc_year = models.CharField(max_length=4,null=True, blank=True)
    description = models.TextField(null=True)
    team_size = models.CharField(choices=TEAM_SIZE, max_length=10, null=True, blank=True)
    location = models.CharField(max_length=250, null=True, blank=True)
    trending = models.NullBooleanField(default=False)
    rank = models.IntegerField(default=0, blank=True)
    approval_status = models.PositiveIntegerField(choices=APPROVAL_STATUS_CHOICES, default=0)
    company_tagline = models.CharField(max_length=200, blank=True)
    trending_reason = models.CharField(max_length=200, blank=True, null=True)
    chat_password = models.CharField(max_length=8, null=True, blank=True)
    chat_user = models.CharField(max_length=50, null=True, blank=True)
    identity_token = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.name_of_startup

portal/dashboard/forms.py
from django import forms


from startups.models import startUp


class LoginForm(forms.Form):
    username = forms.EmailField(max_length=50, required=True)
    password = forms.CharField(max_length=15, widget=forms.PasswordInput)


class AddEventForm(forms.Form):
    name_of_event = forms.CharField(max_length=200, label='Name of Event :', required=True)
    # hosted_by_startup = forms.ModelChoiceField(queryset=startUp.objects.all(), required=False)
    # hosted_by_mentor = forms.ModelChoiceField(queryset=Mentor.objects.all(), required=False)
    hosted_by = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, required=True)
    location = forms.CharField(max_length=100)
    start_date = forms.DateTimeField(required=True)
    end_date = forms.DateTimeField(required=True)
    public_url = forms.URLField(max_length=500, required=False)
    event_image = forms.FileField(required=False)


class AddStartupForm(forms.Form):
    TEAM_SIZE = (
        ('None', 'None'),
        ('0-10', '0-10'),
        ('10+', '10+'),
        ('20+', '20+'),
        ('30+', '30+'),
        ('40+', '40+'),
        ('50+', '50+')
    )
    TYPE_OF_TRADE = (
        ('None', 'None'),
        ('Technology', 'Technology'),
        ('Logistics', 'Logistics'),
        ('Marketing', 'Marketing'),
        ('Ecommerce', 'Ecommerce'),
        ('Services', 'Services')
    )
    name_of_startup = forms.CharField(max_length=100, label='Name of Startup', required=True)
    startup_logo = forms.ImageField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    company_website = forms.URLField(required=False)
    twitter_handle = forms.CharField(max_length=50, required=False)
    inc_year = forms.IntegerField(required=False)
    type_of_trade = forms.ChoiceField(choices=TYPE_OF_TRADE, widget=forms.Select(), required=True)
    description = forms.CharField(widget=forms.Textarea, required=False)
    team_size = forms.ChoiceField(choices=TEAM_SIZE, widget=forms.Select(), required=False)
    location = forms.CharField(max_length=250, required=False)
    company_tagline = forms.CharField(max_length=100, required=False)


class AddUserForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)
    email = forms.EmailField(required=True)
    image = forms.FileField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_handle = forms.URLField(required=False)
    startup = forms.ModelChoiceField(queryset=startUp.objects.all())
    add_another_founder = forms.BooleanField(required=False)
    about = forms.CharField(widget=forms.Textarea, required=False)


class AddMentorForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)
    email = forms.EmailField(required=True)
    image = forms.FileField(required=False)
    linkedin_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    twitter_handle = forms.URLField(required=False)
    company_name = forms.CharField(max_length=200, required=False)
    expertise = forms.CharField(max_length=100, required=False)
    past_experience = forms.CharField(widget=forms.Textarea, required=False)
    about = forms.CharField(widget=forms.Textarea, required=False)

portal/startups/forms.py
#Django Related imports
from django import forms
from django.forms import ModelForm

#Model imports

from .models import startUp



class AddStartupForm(forms.Form):
    TEAM_SIZE = (
        ('None', 'None'),
        ('0-10', '0-10'),
        ('10+', '10+'),
        ('20+', '20+'),
        ('30+', '30+'),
        ('40+', '40+'),
        ('50+', '50+')
    )
    TYPE_OF_TRADE = (
        ('None', 'None'),
        ('Technology', 'Technology'),
        ('Logistics', 'Logistics'),
        ('Marketing', 'Marketing'),
        ('Ecommerce', 'Ecommerce'),
        ('Services', 'Services')
    )

    name_of_startup      = forms.CharField(max_length= 100, label = 'Name of Startup', required = True)
    startup_logo         = forms.ImageField(required = False)
    linkedin_url         = forms.URLField(required=False)
    facebook_url         = forms.URLField(required=False)
    company_website      = forms.URLField(required=True)
    twitter_handle       = forms.CharField(max_length=50, required=False)
    inc_year             = forms.IntegerField(required = True)
    type_of_trade        = forms.ChoiceField(choices=TYPE_OF_TRADE,widget = forms.Select(), required = True)
    description          = forms.CharField(widget=forms.Textarea,required = True)
    team_size            = forms.ChoiceField(choices=TEAM_SIZE, widget = forms.Select(), required = False)
    location             = forms.CharField(max_length=200, required = True)
    company_tagline      = forms.CharField(max_length=100, required = False)

portal/dashboard/templates/dashboard/addevent.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% block head %}
{{ block.super }}
{% block title %} <title>AddEvent</title>{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'css/addevent.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.geocomplete.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?&sensor=false&libraries=places&key=AIzaSyCNrQsPssxdFOI8YCO7TwLnM0YTPasLW2k"></script>
<script type="text/javascript">


  function handleFileSelect() {
    var files = $('#id_event_image')[0].files;

    // Loop through the FileList and render image files as thumbnails.
    for (var i = 0, f; f = files[i]; i++) {

      // Only process image files.
      if (!f.type.match('image.*')) {
        continue;
      }

      var reader = new FileReader();

      // Closure to capture the file information.
      reader.onload = (function(theFile) {

        return function(e) {
          // Render thumbnail.
          var span = document.createElement('span');
          span.innerHTML = 
          [

          '<img style="height: 75px;  margin: 5px" src="', 
          e.target.result,
          '" title="', escape(theFile.name), 
          '"/>'
          ].join('');
          $('#list').show();
          document.getElementById('list').insertBefore(span, null);
        };
      })(f);

      // Read in the image file as a data URL.
      reader.readAsDataURL(f);
    }
  }


  $(function () { 
    $("#id_location").geocomplete({
      details: ".geo-details",
      detailsAttribute: "data-geo"
    });
  });


</script>
{% endblock head %}

{% block content %}
<div class='container'>
    <div class='padding-container-regular'>

        <div class="row">
            <div class="row-md-12">
                <h2 class="center font-prop" style="text-align:center;">
                    ADD EVENT
                </h2>
                <form method="POST" action=""  enctype="multipart/form-data">
          {% csrf_token %}
          <div  class="form-element">
            <label>Name of Event</label>
            <input id="id_name_of_event" maxlength="200" name="name_of_event" type="text" />
            {{form.name_of_event.errors}}
          </div>
          <div class="form-element">
            <label>Hosted By </label>
            {{form.hosted_by}}
            {{form.hosted_by.errors}}
          </div>
          <div class="form-element">
            <label>Description</label>
            <textarea  id="id_description" name="description" rows="5">
            </textarea>
            {{form.description.errors}}
          </div>
          <div class="form-element">
            <label>Location</label>
            <input id="id_location" maxlength="100" name="location" type="text" />
            {{form.location.errors}}
          </div>
          <div class="form-element">
            <label>Start Date</label>
            <input id="id_start_date" type="datetime-local" name="start_date"  step=1 />
            {{form.start_date.errors}}

          </div>
          <div class="form-element">
            <label>End Date</label>
            <input id="id_end_date" type="datetime-local" name="end_date" step=1 />
            {{form.end_date.errors}}
          </div>
          <div class="form-element">
            <label>Image</label>
            <input id="id_event_image"  class="custom-file-input" name="event_image" type="file"  onchange="handleFileSelect()">
            <output id="list"></output>
          </div>
          {{form.event_image.errors}}
          <div class="form-element">
            <label>Public URL</label>
            <input id="id_public_url" maxlength="500" name="public_url" type="url" />
            {{form.publice_url.errors}}
          </div>

          <div class="form-element submit" >
            <input type="submit" value="Save " class="btn btn-submit"  id="save"  />
          </div>

        </form>
            </div>
        </div>

    </div>
</div>
{% endblock content %}


{% block script %}
{{block.super}}
{% endblock script %}

portal/dashboard/templates/dashboard/addstartup.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% block head %}
{{ block.super }}
{% block title %}
<title>Founder|Add Startup</title>
{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'css/addstartup.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.geocomplete.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?&sensor=false&libraries=places"></script>
<script type="text/javascript">


  function handleFileSelect() {
    var files = $('#id_startup_logo')[0].files;

    // Loop through the FileList and render image files as thumbnails.
    for (var i = 0, f; f = files[i]; i++) {

      // Only process image files.
      if (!f.type.match('image.*')) {
        continue;
      }

      var reader = new FileReader();

      // Closure to capture the file information.
      reader.onload = (function(theFile) {

        return function(e) {
          // Render thumbnail.
          var span = document.createElement('span');
          span.innerHTML = 
          [

          '<img style="height: 75px;  margin: 5px" src="', 
          e.target.result,
          '" title="', escape(theFile.name), 
          '"/>'
          ].join('');
          $('#list').show();
          document.getElementById('list').insertBefore(span, null);
        };
      })(f);

      // Read in the image file as a data URL.
      reader.readAsDataURL(f);
    }
  }


  $(function () { 
    $("#id_location").geocomplete({
      details: ".geo-details",
      detailsAttribute: "data-geo"
    });
  });



</script>
{% endblock head %}

{% block content %}

<div class='container'>
    <div class='padding-container-regular'>

        <div class="row">
            <div class="row-md-12">
                <h2 class="center font-prop" style="text-align:center;">
                    ADD STARTUP
                </h2>
                <form enctype="multipart/form-data" method="POST" action="">
                    {% csrf_token %}

                    <div id="name_of_startup" class="row form-element">
                        <label id="label_name_of_startup">Name of Startup</label><span class="required">*</span>
                        <div class="input">
                            <input type="text" id="id_name_of_startup" name="name_of_startup">
                            <div class="errors">
                                {{form.name_of_startup.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="startup_logo" class="row form-element">
                        <label>Startup Logo</label><span class="required">*</span>
                        <div>
                            <input id="id_startup_logo" name="startup_logo" class="custom-file-input" type="file" onchange="handleFileSelect()">
                            <output id="list"></output>
                            <div class="errors">
                                {{form.startup_logo.errors}}
                            </div>
                        </div>
                    </div>

                    <div id="company_website" class="row form-element">
                        <label>Company Website</label><span class="required">*</span>
                        <div class="input">
                            <input type="url" id="id_company_website" name="company_website" placeholder="Use protocol(http or https)">
                            <div class="errors">
                                {{form.company_website.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="linkedin" class="row form-element">
                        <label>Linkedin Url</label>
                        <div class="input">
                            <input type="url" id="id_linkedin_url" name="linkedin_url" placeholder="Use https"/>
                            <div class="errors">
                                {{form.linkedin_url.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="facebook" class="row form-element">
                        <label>Facebook Url</label>
                        <div class="input">
                            <input type="url" id="id_facebook_url" name="facebook_url" placeholder="Use https">
                            <div class="errors">
                                {{form.facebook_url.errors}}
                            </div>
                        </div>
                    </div>

                    <div id="twitter" class="row form-element">
                        <label>Twitter Handle</label>
                        <div class="input">
                            <input type="url" id="id_twitter_handle" name="twitter_handle" placeholder="Use https">
                            <div class="errors">
                                {{form.twitter_handle.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="description" class="row form-element">
                        <label>Description</label> <span class="required">*</span>
                        <div class="input">
                            <textarea rows="5" id="id_description" name="description"></textarea>

                            <div class="errors">
                                {{form.description.errors}}
                            </div>
                        </div>
                    </div>

                    <div id="location" class="row form-element">
                        <label>Location</label> <span class="required">*</span>
                        <div class="input">
                            <input type="text" name="location" id="id_location">

                            <div class="errors">
                                {{form.location.errors}}
                            </div>
                        </div>
                    </div>

                    <div id="inc_year" class="row form-element">
                        <label>Inc Year</label>
                        <div class="input">
                            <input type="text" name="inc_year" id="id_inc_year">

                            <div class="errors">
                                {{form.inc_year.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="team_size" class="row form-element">
                        <label>Team Size</label>
                        <div class="input">
                            {{form.team_size}}

                            <div class="errors">
                                {{form.team_size.errors}}
                            </div>
                        </div>
                    </div>
                    <div id="type_of_trade" class="row form-element">

                        <label>Type of Trade</label> <span class="required">*</span>
                        <div class="input">
                            {{form.type_of_trade}}

                            <div class="errors">
                                {{form.type_of_trade.errors}}
                            </div>
                        </div>

                    </div>
                    <div id="company_tagline" class="row form-element">
                        <label>Company Tagline</label>
                        <div class="input">
                            <input type="text" name="company_tagline" id="id_company_tagline">
                            <!-- <div class="errors">
                                {{form.tagline.errors}}
                              </div> -->
                        </div>
                    </div>

                    <div class="row form-element">
                        <input type="submit" value="Save" class="btn btn-submit center-block" id="save"/>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>
{% endblock content %}


{% block script %}
{{block.super}}
<script type="text/javascript">
              $(function(){
                $('#id_company_tagline').keyup(function(){

                  var temp = $('#id_company_tagline').val();
                  var temp = temp.split(' ');
                  if (temp.length>5)
                  {
                    $('#tagline_error').show();

                    setTimeout(function(){
                      $('#id_company_tagline').focus();},1000);
                  }
                  if (temp.length<=5){
                    $('#tagline_error').hide();
                  }
                });
              });

</script>
<!--
<script type="text/javascript">
              $( "#id_facebook_url" ).val('https://' );
              $( "#id_linkedin_url" ).val('https://' );
              $( "#id_twitter_handle" ).val('https://' );
              $( "#id_company_website" ).val('http://');
            </script>-->


{% endblock script %}

portal/dashboard/templates/dashboard/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
{% block head %}
{% load staticfiles%}
<head>
    {% block title %} <title>{{title}}</title>{% endblock %}
    {% comment %} Link CSS Files {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <link rel='stylesheet' type="text/css" href="{% static 'css/normalize.css' %}"/>
    <link rel='stylesheet' type="text/css" href="{% static 'css/finre.css' %}"/>
    <link rel='stylesheet' type="text/css" href="{% static 'css/fa/css/font-awesome.min.css'%}"/>



    <style>
    .finre-framework table tr.user-details-pane {
      display: none;
    }
    .finre-framework table tr.user-details-pane td .user-details {
      padding: 0 20px;
      display: inline-block;
      vertical-align: top;
    }
    .finre-framework .navbar ul.nav > li > a {
     color: #444;
   }

   a.pagination {
    display: inline-block;
    margin: 0 20px;
    color: #444;
  }
  th.rotate {
    height: 140px;
    white-space: nowrap;
    border-left: none !important;
    border-right: none !important;
    border-top: none !important;
  }

  th.rotate > div {
    transform: rotate(-45deg) translate(-50px, 55px);
    width: 30px;
  }
  th.rotate > div > span {
    border-bottom: 1px solid #ddd;
  }
  th[match], td[match] {
    display: none;
  }

  li :hover
  {
       background-color: transparent !important;
  }
  .logout a, .logout a:hover
  {
    color: black;
    text-decoration: none;
  }
  .navbar-inner
  {
    height: auto !important;
    display:flex!important;
    justify-content:center;
    font-size: 2rem;
  }
  .nav
  {
    color: blue!important;
  }
  .founderbar
  {
  	height:200px;
  	background: -webkit-linear-gradient(left, red , yellow); /* For Safari 5.1 to 6.0 */
  	background: -o-linear-gradient(right, red, yellow); /* For Opera 11.1 to 12.0 */
  	background: -moz-linear-gradient(right, red, yellow); /* For Firefox 3.6 to 15 */
  	background: linear-gradient(to right, #304574 , #4DA6F5); /* Standard syntax */
  	text-align:center;
  	display:flex;
  	flex-direction:column;
  	padding: 37px 0px;
  }
  .founderbar>span{
  	color:white;
  	font-size:2.1rem;
  }
</style>
    {% comment %} Link 3rdParty JavaScript Files {% endcomment %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script   src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"   integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="   crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/modernizr.custom.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/css_browser_selector.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>


</head>
{% endblock head %}
<body class='finre-framework'>
{% block navbar %}
<div class="navbar">
	<div class="founderbar">
    <div>
      <img style="height:100px;width:100px;" src="{% static 'images/f_logo.png' %}">
    </div>
      <span>FOUNDER</span>
    </div>
    <div class="navbar-inner">
        <!--<div>	
            <ul class='nav'><li><a href="/dashboard/startups/1" class="brand">FOUNDER</a></li></ul>
        </div>-->


        <ul class="nav">
            {% if request.user.is_authenticated %}
		        <li><a href='/dashboard/startups/1'>View Startups</a></li>
		        <li><a href='/dashboard/startuprequests/1'>Startup Requests</a></li>
		        <li><a href='/dashboard/posts/1'>View Posts</a></li>
		        <li><a href='/dashboard/events/1'>View Events</a></li>
                <li><a href='/dashboard/mentors/1'>View Mentors</a></li>
                <li><a href='/dashboard/confessions/1'>View Confession</a></li>
		        <li><a href='/dashboard/addevent'>Add Event</a></li>
		        <li><a href='/dashboard/addstartup'>Add Startup</a></li>
		        <li><a href='/dashboard/addfounder'>Add Founder</a></li>
		        <li><a href='/dashboard/addmentor'>Add Mentor</a> </li>
		        <li><a href='/dashboard/startupranklist'>Startup Ranklist</a></li>
            {%endif%}
                <li><a href='/dashboard/logout'>Logout</a></li>
        </ul>

    </div>
</div>
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}


{% block script %}{% endblock script %}
</body>

</html>

portal/dashboard/templates/dashboard/d.html
{% extends "dashboard/base.html" %}

{% block head %}
  {{ block.super }}
{% endblock %}

{% block content %}

<div class='container'>
<span>
  Dashboard content goes here 
</span>
</div>
{% endblock %}

{% block footer %} {{ block.super }} {% endblock %}

portal/dashboard/templates/dashboard/startupapproved.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/startupdetails.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>

{% endblock %}

{% block content %}
  <div class="row">

    <h3>
      The Startup {{startup.name_of_startup}} has been Approved and a mail has been sent to <br>
      it's founders with username and invite_token
    </h3>
      
    </div>
{% endblock content %}